/*
 * Run findCommonLines.ts to see the list of the commonly used lines that you
 * want to exclude
 */
export const removalList = [
  "Advertisement",
  "RECOMMENDED VIDEOS FOR YOU...",
  "Image for post",
  "Quincy Larson",
  "Eric Leung",
  "Karl Hughes",
  "Sam Williams",
  "Jason Evangelho",
  "Milecia McGregor",
  "A version of this article appeared in the “Musk Reads” newsletter. Sign up for free here.",
  "Got any comments or queries? Don’t forget to send them over to muskreads@inverse.com.",
  "logout",
  "Watch on YouTube",
  "ADVERT",
  "Share via",
  "Copy link",
  "Related Topics:",
  "Subscribe to Visual Capitalist",
  "Get your mind blown on a daily basis:",
  "If you read this far, tweet to the author to show them you care. Tweet a thanks",
  "Recommended Reading:",
  "Sponsored Content",
  "Learn to code for free. freeCodeCamp's" +
    " open source curriculum has helped more than 40,000 people get jobs as developers. Get started",
  "Image for post",
  "MORE:",
  "RELATED:",
  "RELATED: ",
  ".",
  "Painting by the author Javier Ideami@ideami.com",
  "Conclusion",
  "Featured Videos From The Verge",
  "If you buy something from a Verge link, Vox Media may earn a commission. See our ethics statement.",
  "More from The Verge",
  "(Image credit: Shutterstock)",
  "Credit",
  "Continue scrolling to keep reading",
  "Click the button below to start this article in quick view.",
  "Getty Images",
  "Final Thoughts",
  "More about",
  "SUMMARY",
  "Related Story",
  "Share this:",
  "Share",
  "KEY FACT",
  "newsletter promo",
  "Sign up for Scientific American’s free newsletters. Sign Up",
  "ADVERTISEMENT",
  "This is an opinion and analysis article; the views expressed by " +
    "the author or authors are not necessarily those of Scientific American.",
  "(Summary of changes)",
  "Merge made by recursive.",
  "Credit: Getty Images",
  "Source",
  "Alexandru Paduraru",
  "Share on LinkedIn",
  "Calendar Icon",
  "Source: Bloomberg",
  "Sign Up",
];

export const regexRemovalList = [/^Last modified on [^\n]+$/u];
